// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campuses.sql

package database

import (
	"context"
	"database/sql"
)

const createCampus = `-- name: CreateCampus :one
INSERT INTO campus (created_at, updated_at, name, location, college_id) 
VALUES (
	NOW(),
	NOW(),
	$1,
	$2,
	$3
)
RETURNING id, name, location, college_id, created_at, updated_at
`

type CreateCampusParams struct {
	Name      string
	Location  sql.NullString
	CollegeID int32
}

func (q *Queries) CreateCampus(ctx context.Context, arg CreateCampusParams) (Campus, error) {
	row := q.db.QueryRowContext(ctx, createCampus, arg.Name, arg.Location, arg.CollegeID)
	var i Campus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CollegeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
