// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Campus struct {
	ID        int32
	Name      string
	Location  sql.NullString
	CollegeID int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type College struct {
	ID          int32
	NameCollege string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedBy   uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
